import { Button } from '@chakra-ui/button'
import { Heading } from '@chakra-ui/layout'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button colorScheme="red">Test</Button>
        <Heading as="h1">H1</Heading>
      </main>

      <footer>
      </footer>
    </div>
  )
}
